# Generated by Django 5.2.8 on 2025-11-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrustedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('SMARTPHONE', 'Smartphone'), ('IOT_SENSOR', 'IoT Sensor'), ('SMART_WATCH', 'Smart Watch'), ('VEHICLE', 'Connected Vehicle'), ('MEDICAL', 'Medical Device')], max_length=20)),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('secret_key', models.CharField(max_length=100)),
                ('security_level', models.CharField(choices=[('LOW', 'Low - Basic IoT'), ('MEDIUM', 'Medium - Personal Devices'), ('HIGH', 'High - Critical Infrastructure'), ('MAXIMUM', 'Maximum - Emergency Services')], default='MEDIUM', max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_authentication', models.DateTimeField(blank=True, null=True)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('is_locked', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Trusted Device',
                'verbose_name_plural': 'Trusted Devices',
            },
        ),
    ]
