# Generated by Django 5.2.8 on 2025-11-22 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zero_trust_demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_failed_attempts', models.IntegerField(default=3)),
                ('session_timeout', models.IntegerField(default=30)),
                ('requires_approval', models.BooleanField(default=True)),
                ('auto_lockout', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='trusteddevice',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='trusteddevice',
            name='is_locked',
        ),
        migrations.AddField(
            model_name='trusteddevice',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trusteddevice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trusteddevice',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='trusteddevice',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended'), ('LOCKED', 'Locked')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='trusteddevice',
            name='device_type',
            field=models.CharField(choices=[('SMARTPHONE', 'Smartphone'), ('IOT_SENSOR', 'IoT Sensor'), ('SMART_WATCH', 'Smart Watch'), ('VEHICLE', 'Connected Vehicle'), ('MEDICAL', 'Medical Device'), ('EMERGENCY', 'Emergency Service'), ('INDUSTRIAL', 'Industrial IoT')], max_length=20),
        ),
        migrations.AlterField(
            model_name='trusteddevice',
            name='security_level',
            field=models.CharField(choices=[('LOW', 'Low - Basic IoT'), ('MEDIUM', 'Medium - Personal Devices'), ('HIGH', 'High - Enterprise'), ('MAXIMUM', 'Maximum - Critical Infrastructure')], default='MEDIUM', max_length=20),
        ),
        migrations.CreateModel(
            name='AuthenticationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zero_trust_demo.trusteddevice')),
            ],
        ),
    ]
