# Generated by Django 5.2.8 on 2025-11-22 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zero_trust_demo', '0002_securitypolicy_remove_trusteddevice_is_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkSlice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slice_id', models.CharField(max_length=50, unique=True)),
                ('slice_type', models.CharField(choices=[('EMERGENCY', 'Emergency Services'), ('VIDEO', 'Video Streaming'), ('IOT', 'IoT Devices'), ('ENTERPRISE', 'Enterprise'), ('PUBLIC', 'Public Safety'), ('INDUSTRIAL', 'Industrial IoT')], max_length=20)),
                ('priority', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=20)),
                ('max_latency', models.IntegerField(help_text='Maximum latency in milliseconds')),
                ('min_bandwidth', models.IntegerField(help_text='Minimum bandwidth in Mbps')),
                ('security_level', models.CharField(choices=[('LOW', 'Low - Basic IoT'), ('MEDIUM', 'Medium - Personal Devices'), ('HIGH', 'High - Enterprise'), ('MAXIMUM', 'Maximum - Critical Infrastructure')], default='HIGH', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Network Slice',
                'verbose_name_plural': 'Network Slices',
            },
        ),
        migrations.CreateModel(
            name='SliceAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('access_granted', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('bandwidth_used', models.FloatField(blank=True, null=True)),
                ('latency', models.FloatField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zero_trust_demo.trusteddevice')),
                ('slice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zero_trust_demo.networkslice')),
            ],
        ),
        migrations.CreateModel(
            name='SliceAccessPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_device_types', models.JSONField(default=list, help_text='List of allowed device types')),
                ('required_security_level', models.CharField(choices=[('LOW', 'Low - Basic IoT'), ('MEDIUM', 'Medium - Personal Devices'), ('HIGH', 'High - Enterprise'), ('MAXIMUM', 'Maximum - Critical Infrastructure')], max_length=20)),
                ('requires_approval', models.BooleanField(default=True)),
                ('slice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zero_trust_demo.networkslice')),
            ],
        ),
    ]
